name: MultiTwitchWhitelist
main: cat.jaffa.multitwitchwhitelist.MultiTwitchWhitelist
version: 0.3
author: Jaffa
description: A Plugin to handle multiple twitch stream whitelisting.

commands:
  mtwl:
    description: Administrate MultiTwitchWhitelist
    usage: /<command> [action]
permissions:
  mtwl.admin:
    description: Gives access to administration of the plugin
    default: op
  mtwl.bypasswhitelist:
    description: Bypasses whitelist requirements
    default: op
  mtwl.bypassban:
    description: Bypasses MultiTwitchWhitelist bans.
    default: op
  mtwl.connectionfailbypass:
    description: Bypasses whitelist when connection to whitelisting site fails